name: seasonthon_team26_fe
description: "[2025 kakao X groom 시즌톤] 26팀 [꿈마중 버스] 프론트엔드"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  provider: ^6.1.1

  # 위치
  geolocator: ^14.0.2

  # 카카오맵
  kakao_maps_flutter: ^0.1.1

  # API 통신
  http: ^1.2.2

  # 로컬 저장소
  shared_preferences: ^2.2.2

  # 외부 링크
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/blue_dot.png
    - assets/images/stop_pin.png
